// frontend/src/features/auth/LoginPage.jsx
import { useMemo, useState } from "react";
import { login } from "./authService";
import { isEmail } from "../../shared/lib/validators";
import "./LoginPage.css";

const MIN_PASSWORD_LENGTH = 6;

const initialValues = {
  email: "",
  password: "",
};

export default function LoginPage({ onSwitch = () => {}, onLogin = () => {} }) {
  const [values, setValues] = useState(initialValues);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");

  const isValid = useMemo(() => {
    return (
      isEmail(values.email) && values.password.length >= MIN_PASSWORD_LENGTH
    );
  }, [values.email, values.password]);

  const handleChange = (event) => {
    const { name, value } = event.target;
    setValues((prev) => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (event) => {
    event.preventDefault();
    setError("");
    setSuccess("");

    if (!isValid) {
      setError("Informe um email e senha validos.");
      return;
    }

    setIsLoading(true);

    try {
      const data = await login(values);
      const userName = data?.user?.name || "Usuario";
      setSuccess(`Bem-vindo de volta, ${userName}.`);
      onLogin(data);
    } catch (err) {
      setError(err.message || "Nao foi possivel entrar.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <section className="auth-shell">
      <div className="auth-hero">
        <span className="auth-chip">Acesso seguro</span>
        <h1>Acesse seu workspace</h1>
        <p>
          Use suas credenciais para acessar o painel e validar o fluxo do
          backend em segundos.
        </p>
        <div className="auth-metrics">
          <div>
            <strong>JWT pronto</strong>
            <span>Tokens de acesso + refresh</span>
          </div>
          <div>
            <strong>Saude da API</strong>
            <span>Health check protegido</span>
          </div>
        </div>
      </div>

      <form className="auth-card" onSubmit={handleSubmit}>
        <div>
          <span className="auth-eyebrow">Bem-vindo</span>
          <h2>Entrar</h2>
          <p>Informe seu email e senha para continuar.</p>
        </div>

        <div className="auth-field">
          <label htmlFor="email">Email</label>
          <input
            id="email"
            name="email"
            type="email"
            autoComplete="email"
            placeholder="seu@email.com"
            value={values.email}
            onChange={handleChange}
            required
          />
        </div>

        <div className="auth-field">
          <label htmlFor="password">Senha</label>
          <input
            id="password"
            name="password"
            type="password"
            autoComplete="current-password"
            placeholder="Minimo 6 caracteres"
            value={values.password}
            onChange={handleChange}
            minLength={MIN_PASSWORD_LENGTH}
            required
          />
        </div>

        {error ? (
          <div className="auth-alert" role="alert">
            {error}
          </div>
        ) : null}

        {success ? (
          <div className="auth-success" role="status" aria-live="polite">
            {success}
          </div>
        ) : null}

        <button className="auth-button" type="submit" disabled={isLoading}>
          {isLoading ? "Entrando..." : "Entrar"}
        </button>

        <p className="auth-hint">
          Use o access token para chamar <span>/health</span>.
        </p>

        <p className="auth-switch">
          Ainda nao tem conta?
          <button type="button" onClick={onSwitch}>
            Criar conta
          </button>
        </p>
      </form>
    </section>
  );
}

// frontend/src/app/pages/auth/login-page.component.ts
import { CommonModule } from "@angular/common";
import { Component, OnInit, inject } from "@angular/core";
import { FormBuilder, ReactiveFormsModule, Validators } from "@angular/forms";
import { Router } from "@angular/router";
import { finalize } from "rxjs";
import { PoButtonType, PoNotificationService } from "@po-ui/ng-components";
import { AuthService } from "../../core/auth.service";
import { PO_UI_MODULES } from "../../shared/po-ui-imports";

@Component({
  selector: "app-login-page",
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, ...PO_UI_MODULES],
  templateUrl: "./login-page.component.html",
  styleUrls: ["./login-page.component.css"],
})
export class LoginPageComponent implements OnInit {
  private fb = inject(FormBuilder);
  readonly submitType = PoButtonType.Submit;
  readonly form = this.fb.group({
    email: ["", [Validators.required, Validators.email]],
    password: ["", [Validators.required, Validators.minLength(6)]],
  });

  isLoading = false;
  errorMessage = "";

  constructor(
    private auth: AuthService,
    private router: Router,
    private notification: PoNotificationService
  ) {}

  ngOnInit(): void {
    if (this.auth.isLoggedIn) {
      void this.router.navigate(["/dashboard"]);
    }
  }

  submit(): void {
    this.errorMessage = "";
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      this.errorMessage = "Informe um email e senha validos.";
      return;
    }

    this.isLoading = true;

    const raw = this.form.getRawValue();
    const email = raw.email ?? "";
    const password = raw.password ?? "";

    this.auth
      .login({ email, password })
      .pipe(finalize(() => (this.isLoading = false)))
      .subscribe({
        next: (session) => {
          this.notification.success(`Bem-vindo, ${session.user?.name || ""}.`);
          void this.router.navigate(["/dashboard"]);
        },
        error: (err) => {
          this.errorMessage =
            err?.error?.error || "Nao foi possivel entrar.";
          this.notification.error(this.errorMessage);
        },
      });
  }

  goToRegister(): void {
    void this.router.navigate(["/register"]);
  }
}

<po-page-default
  p-title="Acesse seu workspace"
  p-subtitle="Entre com sua conta para acompanhar o status da API."
>
  <div class="auth-layout">
    <section class="auth-hero">
      <span class="auth-chip">Acesso seguro</span>
      <h2>Controle total em um painel unificado</h2>
      <p>
        Visualize tokens, health checks e usuários a partir de um fluxo Angular
        completo com PO UI.
      </p>
      <div class="auth-metrics">
        <div>
          <strong>JWT pronto</strong>
          <span>Tokens de acesso + refresh</span>
        </div>
        <div>
          <strong>API protegida</strong>
          <span>Endpoints com guards</span>
        </div>
      </div>
    </section>

    <po-container class="auth-card">
      <form class="auth-form" [formGroup]="form" (ngSubmit)="submit()">
        <div>
          <span class="auth-eyebrow">Bem-vindo</span>
          <h3>Entrar</h3>
          <p>Informe seu email e senha para continuar.</p>
        </div>

        <po-input
          p-label="Email"
          p-placeholder="seu@email.com"
          formControlName="email"
        ></po-input>

        <po-password
          p-label="Senha"
          p-placeholder="Minimo 6 caracteres"
          formControlName="password"
        ></po-password>

        <p class="auth-error" *ngIf="errorMessage">{{ errorMessage }}</p>

        <po-button
          p-label="Entrar"
          p-kind="primary"
          [p-type]="submitType"
          [p-loading]="isLoading"
          [p-disabled]="isLoading || form.invalid"
        ></po-button>

        <div class="auth-footer">
          <span>Ainda nao tem conta?</span>
          <button type="button" class="auth-link" (click)="goToRegister()">
            Criar conta
          </button>
        </div>
      </form>
    </po-container>
  </div>
</po-page-default>
