// frontend/src/features/admin/AdminUsers.jsx
import { useEffect, useMemo, useState } from "react";
import { listUsers, setUserActive } from "./adminService";
import "./AdminUsers.css";

export default function AdminUsers({ accessToken = "" }) {
  const [users, setUsers] = useState([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState("");
  const [updatingId, setUpdatingId] = useState(null);

  const canLoad = useMemo(() => Boolean(accessToken), [accessToken]);

  const loadUsers = async () => {
    if (!canLoad) {
      setError("Token nao encontrado. Faca login novamente.");
      return;
    }

    setIsLoading(true);
    setError("");

    try {
      const data = await listUsers(accessToken);
      setUsers(data);
    } catch (err) {
      setError(err.message || "Nao foi possivel carregar usuarios.");
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    loadUsers();
  }, [accessToken]);

  const handleToggle = async (user) => {
    if (!user) return;
    setUpdatingId(user.id);
    setError("");

    try {
      const updated = await setUserActive(accessToken, user.id, !user.isActive);
      setUsers((prev) =>
        prev.map((item) => (item.id === updated.id ? updated : item))
      );
    } catch (err) {
      setError(err.message || "Nao foi possivel atualizar o usuario.");
    } finally {
      setUpdatingId(null);
    }
  };

  return (
    <div className="admin-users">
      <div className="admin-users__header">
        <div>
          <h2>Usuarios</h2>
          <p>Ative ou desative acessos conforme necessario.</p>
        </div>
        <button type="button" onClick={loadUsers} disabled={isLoading}>
          {isLoading ? "Atualizando..." : "Atualizar lista"}
        </button>
      </div>

      {error ? (
        <div className="admin-users__alert" role="alert">
          {error}
        </div>
      ) : null}

      <div className="admin-users__table">
        <div className="admin-users__row admin-users__row--head">
          <span>Usuario</span>
          <span>Email</span>
          <span>Role</span>
          <span>Status</span>
          <span>Acoes</span>
        </div>

        {users.length === 0 && !isLoading ? (
          <div className="admin-users__empty">
            Nenhum usuario encontrado.
          </div>
        ) : null}

        {users.map((user) => (
          <div key={user.id} className="admin-users__row">
            <span>{user.name}</span>
            <span>{user.email}</span>
            <span className="admin-users__pill">{user.role}</span>
            <span className={user.isActive ? "is-active" : "is-inactive"}>
              {user.isActive ? "Ativo" : "Inativo"}
            </span>
            <button
              type="button"
              className={user.isActive ? "btn-danger" : "btn-success"}
              onClick={() => handleToggle(user)}
              disabled={updatingId === user.id}
            >
              {updatingId === user.id
                ? "Salvando..."
                : user.isActive
                ? "Desativar"
                : "Ativar"}
            </button>
          </div>
        ))}
      </div>
    </div>
  );
}

// frontend/src/app/pages/admin/admin-users.component.ts
import { CommonModule } from "@angular/common";
import { Component, OnInit } from "@angular/core";
import {
  PoNotificationService,
  PoPageAction,
  PoTableAction,
  PoTableColumn,
} from "@po-ui/ng-components";
import { AdminService } from "../../core/admin.service";
import { AuthService } from "../../core/auth.service";
import { User } from "../../core/models";
import { PO_UI_MODULES } from "../../shared/po-ui-imports";

@Component({
  selector: "app-admin-users",
  standalone: true,
  imports: [CommonModule, ...PO_UI_MODULES],
  templateUrl: "./admin-users.component.html",
  styleUrls: ["./admin-users.component.css"],
})
export class AdminUsersComponent implements OnInit {
  users: User[] = [];
  isLoading = false;
  errorMessage = "";

  readonly columns: PoTableColumn[] = [
    { property: "name", label: "Usuario" },
    { property: "email", label: "Email" },
    { property: "role", label: "Role" },
    {
      property: "isActive",
      label: "Status",
      type: "boolean",
      boolean: { trueLabel: "Ativo", falseLabel: "Inativo" },
    },
  ];

  readonly actions: PoTableAction[] = [
    {
      label: "Ativar",
      action: (row: User) => this.toggleUser(row, true),
      visible: (row: User) => !row.isActive,
    },
    {
      label: "Desativar",
      action: (row: User) => this.toggleUser(row, false),
      type: "danger",
      visible: (row: User) => row.isActive,
    },
  ];

  readonly pageActions: PoPageAction[] = [
    {
      label: "Atualizar lista",
      icon: "po-icon-refresh",
      action: () => this.loadUsers(),
    },
  ];

  get totalUsersLabel(): string {
    return String(this.users.length);
  }

  get activeUsersLabel(): string {
    return String(this.users.filter((user) => user.isActive).length);
  }

  get inactiveUsersLabel(): string {
    return String(this.users.filter((user) => !user.isActive).length);
  }

  constructor(
    private admin: AdminService,
    private auth: AuthService,
    private notification: PoNotificationService
  ) {}

  ngOnInit(): void {
    this.loadUsers();
  }

  loadUsers(): void {
    const token = this.auth.accessToken;
    if (!token) {
      this.errorMessage = "Token nao encontrado. Faca login novamente.";
      return;
    }

    this.isLoading = true;
    this.errorMessage = "";

    this.admin.listUsers(token).subscribe({
      next: (users) => {
        this.users = users;
        this.isLoading = false;
      },
      error: (err) => {
        this.errorMessage =
          err?.error?.error || "Nao foi possivel carregar usuarios.";
        this.notification.error(this.errorMessage);
        this.isLoading = false;
      },
    });
  }

  toggleUser(user: User, isActive: boolean): void {
    if (!user) return;
    const token = this.auth.accessToken;
    if (!token) {
      this.errorMessage = "Token nao encontrado. Faca login novamente.";
      return;
    }

    this.isLoading = true;
    this.errorMessage = "";

    this.admin.setUserActive(token, user.id, isActive).subscribe({
      next: (updated) => {
        if (!updated) {
          this.isLoading = false;
          return;
        }
        this.users = this.users.map((item) =>
          item.id === updated.id ? updated : item
        );
        this.notification.success("Usuario atualizado.");
        this.isLoading = false;
      },
      error: (err) => {
        this.errorMessage =
          err?.error?.error || "Nao foi possivel atualizar o usuario.";
        this.notification.error(this.errorMessage);
        this.isLoading = false;
      },
    });
  }
}

<po-page-default
  p-title="Usuarios"
  p-subtitle="Gerencie acessos e status com controle total."
  [p-actions]="pageActions"
>
  <div class="admin-summary">
    <po-info
      p-label="Total de usuarios"
      [p-value]="totalUsersLabel"
    ></po-info>
    <po-info
      p-label="Ativos"
      [p-value]="activeUsersLabel"
    ></po-info>
    <po-info
      p-label="Inativos"
      [p-value]="inactiveUsersLabel"
    ></po-info>
  </div>

  <p class="admin-error" *ngIf="errorMessage">{{ errorMessage }}</p>

  <po-table
    [p-columns]="columns"
    [p-items]="users"
    [p-actions]="actions"
    [p-loading]="isLoading"
  ></po-table>
</po-page-default>
