// frontend/src/app/pages/auth/register-page.component.ts
import { CommonModule } from "@angular/common";
import { Component, OnDestroy, inject } from "@angular/core";
import { FormBuilder, ReactiveFormsModule, Validators } from "@angular/forms";
import { Router } from "@angular/router";
import { finalize } from "rxjs";
import { PoButtonType, PoNotificationService } from "@po-ui/ng-components";
import { AuthService } from "../../core/auth.service";
import { PO_UI_MODULES } from "../../shared/po-ui-imports";

@Component({
  selector: "app-register-page",
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, ...PO_UI_MODULES],
  templateUrl: "./register-page.component.html",
  styleUrls: ["./register-page.component.css"],
})
export class RegisterPageComponent implements OnDestroy {
  private fb = inject(FormBuilder);
  readonly submitType = PoButtonType.Submit;
  readonly form = this.fb.group({
    name: ["", [Validators.required, Validators.minLength(2)]],
    email: ["", [Validators.required, Validators.email]],
    password: ["", [Validators.required, Validators.minLength(6)]],
    confirmPassword: ["", [Validators.required, Validators.minLength(6)]],
  });

  isLoading = false;
  errorMessage = "";
  private redirectTimer?: number;

  constructor(
    private auth: AuthService,
    private router: Router,
    private notification: PoNotificationService
  ) {}

  ngOnDestroy(): void {
    if (this.redirectTimer) {
      window.clearTimeout(this.redirectTimer);
    }
  }

  submit(): void {
    this.errorMessage = "";
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      this.errorMessage =
        "Preencha nome, email valido e senha com minimo 6 caracteres.";
      return;
    }

    if (this.form.value.password !== this.form.value.confirmPassword) {
      this.errorMessage = "As senhas nao conferem.";
      return;
    }

    this.isLoading = true;

    const raw = this.form.getRawValue();
    const name = raw.name ?? "";
    const email = raw.email ?? "";
    const password = raw.password ?? "";

    this.auth
      .register({ name, email, password })
      .pipe(finalize(() => (this.isLoading = false)))
      .subscribe({
        next: (session) => {
          this.notification.success(
            `Usuario criado. Bem-vindo, ${session.user?.name || ""}.`
          );
          this.form.reset();
          this.redirectTimer = window.setTimeout(() => {
            void this.router.navigate(["/login"]);
          }, 1400);
        },
        error: (err) => {
          this.errorMessage =
            err?.error?.error || "Nao foi possivel cadastrar.";
          this.notification.error(this.errorMessage);
        },
      });
  }

  goToLogin(): void {
    void this.router.navigate(["/login"]);
  }
}

<po-page-default
  p-title="Crie sua conta"
  p-subtitle="Cadastre seus dados para testar o fluxo de autenticação."
>
  <div class="auth-layout">
    <section class="auth-hero">
      <span class="auth-chip">Novo acesso</span>
      <h2>Ative sua conta em minutos</h2>
      <p>
        Receba os tokens de acesso e valide o health check protegido com
        facilidade.
      </p>
      <div class="auth-metrics">
        <div>
          <strong>Cadastro rapido</strong>
          <span>Nome, email e senha</span>
        </div>
        <div>
          <strong>Login imediato</strong>
          <span>Volte ao painel em segundos</span>
        </div>
      </div>
    </section>

    <po-container class="auth-card">
      <form class="auth-form" [formGroup]="form" (ngSubmit)="submit()">
        <div>
          <span class="auth-eyebrow">Bem-vindo</span>
          <h3>Criar conta</h3>
          <p>Informe seus dados para continuar.</p>
        </div>

        <po-input
          p-label="Nome"
          p-placeholder="Seu nome completo"
          formControlName="name"
        ></po-input>

        <po-input
          p-label="Email"
          p-placeholder="seu@email.com"
          formControlName="email"
        ></po-input>

        <po-password
          p-label="Senha"
          p-placeholder="Minimo 6 caracteres"
          formControlName="password"
        ></po-password>

        <po-password
          p-label="Confirmar senha"
          p-placeholder="Repita a senha"
          formControlName="confirmPassword"
        ></po-password>

        <p class="auth-error" *ngIf="errorMessage">{{ errorMessage }}</p>

        <po-button
          p-label="Criar conta"
          p-kind="primary"
          [p-type]="submitType"
          [p-loading]="isLoading"
          [p-disabled]="isLoading || form.invalid"
        ></po-button>

        <div class="auth-footer">
          <span>Ja tem conta?</span>
          <button type="button" class="auth-link" (click)="goToLogin()">
            Entrar
          </button>
        </div>
      </form>
    </po-container>
  </div>
</po-page-default>

// frontend/src/features/auth/RegisterPage.jsx
import { useEffect, useMemo, useRef, useState } from "react";
import { register } from "./authService";
import { isEmail } from "../../shared/lib/validators";
import "./LoginPage.css";

const MIN_PASSWORD_LENGTH = 6;

const initialValues = {
  name: "",
  email: "",
  password: "",
  confirmPassword: "",
};

export default function RegisterPage({ onSwitch = () => {} }) {
  const [values, setValues] = useState(initialValues);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const redirectTimeoutRef = useRef(null);

  const isValid = useMemo(() => {
    return (
      values.name.trim().length >= 2 &&
      isEmail(values.email) &&
      values.password.length >= MIN_PASSWORD_LENGTH &&
      values.password === values.confirmPassword
    );
  }, [values]);

  const handleChange = (event) => {
    const { name, value } = event.target;
    setValues((prev) => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (event) => {
    event.preventDefault();
    setError("");
    setSuccess("");
    if (redirectTimeoutRef.current) {
      clearTimeout(redirectTimeoutRef.current);
      redirectTimeoutRef.current = null;
    }

    if (!isValid) {
      if (values.password !== values.confirmPassword) {
        setError("As senhas nao conferem.");
      } else {
        setError("Preencha nome, email valido e senha com minimo 6 caracteres.");
      }
      return;
    }

    setIsLoading(true);

    try {
      const data = await register(values);
      const userName = data?.user?.name || "Usuario";
      setSuccess(`Usuario criado. Bem-vindo, ${userName}. Redirecionando...`);
      setValues(initialValues);
      redirectTimeoutRef.current = setTimeout(() => {
        onSwitch();
      }, 1500);
    } catch (err) {
      setError(err.message || "Nao foi possivel cadastrar.");
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    return () => {
      if (redirectTimeoutRef.current) {
        clearTimeout(redirectTimeoutRef.current);
      }
    };
  }, []);

  return (
    <section className="auth-shell">
      <div className="auth-hero">
        <span className="auth-chip">Novo acesso</span>
        <h1>Crie sua conta</h1>
        <p>
          Cadastre seus dados para liberar o acesso e testar o fluxo do backend
          com tokens JWT.
        </p>
        <div className="auth-metrics">
          <div>
            <strong>Cadastro rapido</strong>
            <span>Nome, email e senha</span>
          </div>
          <div>
            <strong>Pronto para testar</strong>
            <span>Health check protegido</span>
          </div>
        </div>
      </div>

      <form className="auth-card" onSubmit={handleSubmit}>
        <div>
          <span className="auth-eyebrow">Bem-vindo</span>
          <h2>Criar conta</h2>
          <p>Informe seus dados para continuar.</p>
        </div>

        <div className="auth-field">
          <label htmlFor="name">Nome</label>
          <input
            id="name"
            name="name"
            type="text"
            autoComplete="name"
            placeholder="Seu nome completo"
            value={values.name}
            onChange={handleChange}
            required
          />
        </div>

        <div className="auth-field">
          <label htmlFor="email">Email</label>
          <input
            id="email"
            name="email"
            type="email"
            autoComplete="email"
            placeholder="seu@email.com"
            value={values.email}
            onChange={handleChange}
            required
          />
        </div>

        <div className="auth-field">
          <label htmlFor="password">Senha</label>
          <input
            id="password"
            name="password"
            type="password"
            autoComplete="new-password"
            placeholder="Minimo 6 caracteres"
            value={values.password}
            onChange={handleChange}
            minLength={MIN_PASSWORD_LENGTH}
            required
          />
        </div>

        <div className="auth-field">
          <label htmlFor="confirmPassword">Confirmar senha</label>
          <input
            id="confirmPassword"
            name="confirmPassword"
            type="password"
            autoComplete="new-password"
            placeholder="Repita a senha"
            value={values.confirmPassword}
            onChange={handleChange}
            minLength={MIN_PASSWORD_LENGTH}
            required
          />
        </div>

        {error ? (
          <div className="auth-alert" role="alert">
            {error}
          </div>
        ) : null}

        {success ? (
          <div className="auth-success" role="status" aria-live="polite">
            {success}
          </div>
        ) : null}

        <button className="auth-button" type="submit" disabled={isLoading}>
          {isLoading ? "Criando conta..." : "Criar conta"}
        </button>

        <p className="auth-hint">
          Depois do cadastro, use o login para testar <span>/health</span>.
        </p>

        <p className="auth-switch">
          Ja tem conta?
          <button type="button" onClick={onSwitch}>
            Entrar
          </button>
        </p>
      </form>
    </section>
  );
}
